"""Pinned external repositories and directly downloadable checkpoints.

The 19-family survey panel lives in ``sgg_core/models/model_panel.json``.
This smaller asset catalog contains only links that the downloader can fetch
without fabricating missing URLs. An asset is not an integrated model until a
strict official adapter manifest passes the paper protocol.
"""

REPOSITORIES = {
    "reltr": {
        "url": "https://github.com/yrcong/RelTR.git",
        "commit": "fca7397e9aaeccd95541e83afa4b971f3fa89014",
        "directory": "RelTR",
        "archive_url": "https://codeload.github.com/yrcong/RelTR/tar.gz/fca7397e9aaeccd95541e83afa4b971f3fa89014",
    },
    "microsoft_sgg": {
        "url": "https://github.com/microsoft/scene_graph_benchmark.git",
        "commit": "8e14944f3cc9f178b1c5626482fad509068f1395",
        "directory": "microsoft_scene_graph_benchmark",
        "archive_url": "https://codeload.github.com/microsoft/scene_graph_benchmark/tar.gz/8e14944f3cc9f178b1c5626482fad509068f1395",
    },
    "gpsnet": {
        "url": "https://github.com/siml3/GPS-Net.git",
        "commit": "dfbe63a793026b231b3cd60073aaa91a2ad4d06a",
        "directory": "GPS-Net",
        "archive_url": "https://codeload.github.com/siml3/GPS-Net/tar.gz/dfbe63a793026b231b3cd60073aaa91a2ad4d06a",
    },
    "kaihua_sgg": {
        "url": "https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch.git",
        "commit": "ceb71fa88461c2a97a6258a80f47669d89207296",
        "directory": "Scene-Graph-Benchmark.pytorch",
        "archive_url": "https://codeload.github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch/tar.gz/ceb71fa88461c2a97a6258a80f47669d89207296",
    },
    "kern": {
        "url": "https://github.com/yuweihao/KERN.git",
        "commit": "de654c09c92dd57f11bedf859d3f760f5de90e31",
        "directory": "KERN",
        "archive_url": "https://codeload.github.com/yuweihao/KERN/tar.gz/de654c09c92dd57f11bedf859d3f760f5de90e31",
    },
    "openpsg": {
        "url": "https://github.com/Jingkang50/OpenPSG.git",
        "commit": "34b2a892f7441966265e3d60ad01ee8eeae89041",
        "directory": "OpenPSG",
        "archive_url": "https://codeload.github.com/Jingkang50/OpenPSG/tar.gz/34b2a892f7441966265e3d60ad01ee8eeae89041",
    },
    "pysgg": {
        "url": "https://github.com/SHTUPLUS/PySGG.git",
        "commit": "a63942a076932b3756a477cf8919c3b74cd36207",
        "directory": "PySGG",
        "archive_url": "https://codeload.github.com/SHTUPLUS/PySGG/tar.gz/a63942a076932b3756a477cf8919c3b74cd36207",
    },
    "sgtr": {
        "url": "https://github.com/Scarecrow0/SGTR.git",
        "commit": "03bdd6554f12d521807cf95fe6a7daa7d3bb01dc",
        "directory": "SGTR",
        "archive_url": "https://codeload.github.com/Scarecrow0/SGTR/tar.gz/03bdd6554f12d521807cf95fe6a7daa7d3bb01dc",
    },
    "penet": {
        "url": "https://github.com/VL-Group/PENET.git",
        "commit": "9c9f50777c66647799cb7a17dfb855aa98aecd1e",
        "directory": "PENET",
        "archive_url": "https://codeload.github.com/VL-Group/PENET/tar.gz/9c9f50777c66647799cb7a17dfb855aa98aecd1e",
    },
    "ovsgtr": {
        "url": "https://github.com/gpt4vision/OvSGTR.git",
        "commit": "0a6984a4d2d8012fae0420aaa9c71bff8292eac0",
        "directory": "OvSGTR",
        "archive_url": "https://codeload.github.com/gpt4vision/OvSGTR/tar.gz/0a6984a4d2d8012fae0420aaa9c71bff8292eac0",
    },
    "egtr": {
        "url": "https://github.com/naver-ai/egtr.git",
        "commit": "7f87450f32758ed8583948847a8186f2ee8b21e3",
        "directory": "egtr",
        "archive_url": "https://codeload.github.com/naver-ai/egtr/tar.gz/7f87450f32758ed8583948847a8186f2ee8b21e3",
    },
    "pgsg": {
        "url": "https://github.com/SHTUPLUS/Pix2Grp_CVPR2024.git",
        "commit": "cff742070366a6e702a08b71130eb75fcc4d5f7a",
        "directory": "Pix2Grp_CVPR2024",
        "archive_url": "https://codeload.github.com/SHTUPLUS/Pix2Grp_CVPR2024/tar.gz/cff742070366a6e702a08b71130eb75fcc4d5f7a",
    },
    "hiker_sgg": {
        "url": "https://github.com/zhangce01/HiKER-SGG.git",
        "commit": "4bdb5f9ee2896597d9d598962c3883e3542aa127",
        "directory": "HiKER-SGG",
        "archive_url": "https://codeload.github.com/zhangce01/HiKER-SGG/tar.gz/4bdb5f9ee2896597d9d598962c3883e3542aa127",
    },
    "llm4sgg": {
        "url": "https://github.com/rlqja1107/torch-LLM4SGG.git",
        "commit": "5e2be41a31202439db583709caee9d69e072e787",
        "directory": "torch-LLM4SGG",
        "archive_url": "https://codeload.github.com/rlqja1107/torch-LLM4SGG/tar.gz/5e2be41a31202439db583709caee9d69e072e787",
    },
    "apt": {
        "url": "https://github.com/CGCL-codes/APT.git",
        "commit": "93e8bc727b71980b383b189678f1abbc64d5d096",
        "directory": "APT",
        "archive_url": "https://codeload.github.com/CGCL-codes/APT/tar.gz/93e8bc727b71980b383b189678f1abbc64d5d096",
    },
}


MODELS = {
    "causal_motifs_sum_predcls_vg": {
        "repository": "kaihua_sgg",
        "dataset": "vg",
        "architecture": "Causal Motifs-SUM",
        "supported_tasks": ["predcls"],
        "relative_path": "causal_motifs_sum/vg/predcls/model_0030000.pth",
        "download": {
            "kind": "url",
            "url": "https://1drv.ms/u/s!AmRLLNf6bzcir9xx725wYjN7lytynA?e=0B65Ws",
        },
        "download_status": "manual_official_portal",
        "download_note": "Official OneDrive checkpoint; download in a browser and retain the published filename.",
        "reference_metrics": {
            "PredCls/R@50": 66.11,
            "PredCls/mR@50": 14.60,
            "PredCls/zR@50": 11.02,
        },
    },
    "causal_motifs_sum_sgcls_vg": {
        "repository": "kaihua_sgg",
        "dataset": "vg",
        "architecture": "Causal Motifs-SUM",
        "supported_tasks": ["sgcls"],
        "relative_path": "causal_motifs_sum/vg/sgcls/model_final.pth",
        "download": {
            "kind": "url",
            "url": "https://1drv.ms/u/s!AmRLLNf6bzcir9xyuLO_I8TSZ6kfyQ?e=Y5686s",
        },
        "download_status": "manual_official_portal",
        "download_note": "Official OneDrive SGCls checkpoint (resid 22376FFAD72C4B64!781938).",
        "reference_metrics": {
            "SGCls/R@50": 39.25,
            "SGCls/mR@50": 8.02,
            "SGCls/zR@50": 2.18,
        },
    },
    "causal_motifs_sum_sgdet_vg": {
        "repository": "kaihua_sgg",
        "dataset": "vg",
        "architecture": "Causal Motifs-SUM",
        "supported_tasks": ["sgdet"],
        "relative_path": "causal_motifs_sum/vg/sgdet/model_0028000.pth",
        "download": {
            "kind": "url",
            "url": "https://1drv.ms/u/s!AmRLLNf6bzcir9x7OYb6sKBlzoXuYA?e=s3Y602",
        },
        "download_status": "manual_official_portal",
        "download_note": "Official OneDrive checkpoint; download in a browser and retain the published filename.",
        "reference_metrics": {
            "SGDet/R@50": 32.45,
            "SGDet/mR@50": 5.83,
            "SGDet/zR@50": 0.08,
        },
    },
    "kern_sgcls_predcls_vg": {
        "repository": "kern",
        "dataset": "vg",
        "architecture": "KERN",
        "supported_tasks": ["predcls", "sgcls"],
        "relative_path": "kern/vg/kern_sgcls_predcls.tar",
        "download": {"kind": "gdrive", "id": "1F2WBSGRHmJD9K1LT8ImkGOCuZraood21"},
        "download_status": "manual_official_portal",
        "download_note": "The .tar suffix is an old torch.save checkpoint, not a tar archive.",
        "reference_metrics": {
            "PredCls/mR@50": 17.7,
            "PredCls/mR@100": 19.2,
            "SGCls/mR@50": 9.4,
            "SGCls/mR@100": 10.0,
        },
    },
    "kern_sgdet_vg": {
        "repository": "kern",
        "dataset": "vg",
        "architecture": "KERN",
        "supported_tasks": ["sgdet"],
        "relative_path": "kern/vg/kern_sgdet.tar",
        "download": {"kind": "gdrive", "id": "1hAx4MpMiwofABQi9H6_Jb0Qjp016JX7T"},
        "download_status": "manual_official_portal",
        "download_note": "The .tar suffix is an old torch.save checkpoint, not a tar archive.",
        "reference_metrics": {
            "SGDet/mR@50": 6.4,
            "SGDet/mR@100": 7.3,
        },
    },
    "reltr_vg": {
        "repository": "reltr",
        "dataset": "vg",
        "architecture": "RelTR",
        "supported_tasks": ["sgdet"],
        "relative_path": "reltr/vg/checkpoint0149.pth",
        "download": {"kind": "gdrive", "id": "1id6oD_iwiNDD6HyCn2ORgRTIKkPD3tUD"},
        "reference_metrics": {},
    },
    "reltr_oi": {
        "repository": "reltr",
        "dataset": "oi",
        "architecture": "RelTR",
        "supported_tasks": ["sgdet"],
        "relative_path": "reltr/oi/checkpoint0149_oi.pth",
        "download": {"kind": "gdrive", "id": "1pcoUnR0XWsvM9lJZ5f93N5TKHkLdjtnb"},
        "reference_metrics": {},
    },
    "bgnn_vg": {
        "repository": "pysgg",
        "dataset": "vg",
        "architecture": "BGNN",
        "supported_tasks": ["sgdet"],
        "relative_path": "pysgg/vg/bgnn_vg.pth",
        "download": {
            "kind": "url",
            "url": "https://shanghaitecheducn-my.sharepoint.com/:u:/g/personal/lirj2_shanghaitech_edu_cn/Ee4PdxluTphEicUDckJIfmEBisAyUgkjeuerN_rjrG1CIw?e=pgr8a5",
        },
        "download_status": "manual_official_portal",
        "download_note": "Download bgnn_vg.pth from the official PySGG SharePoint page in a browser, then verify and inventory it locally.",
        "reference_metrics": {"SGDet/mR@50": 10.9, "SGDet/R@50": 29.8},
    },
    "bgnn_oi": {
        "repository": "pysgg",
        "dataset": "oi",
        "architecture": "BGNN",
        "supported_tasks": ["sgdet"],
        "relative_path": "pysgg/oi/bgnn_oiv6.pth",
        "download": {
            "kind": "url",
            "url": "https://shanghaitecheducn-my.sharepoint.com/:u:/g/personal/lirj2_shanghaitech_edu_cn/EdKOrWAOf4hMiDWbR3CgYrMB9w7ZwWul-Wc6IUSbs51Idw?e=oEEHIQ",
        },
        "download_status": "manual_official_portal",
        "download_note": "Download the OIv6 BGNN checkpoint from the official PySGG SharePoint page in a browser.",
        "reference_metrics": {"SGDet/mR@50": 41.71, "SGDet/R@50": 74.96},
    },
    "sgtr_vg": {
        "repository": "sgtr",
        "dataset": "vg",
        "architecture": "SGTR",
        "supported_tasks": ["sgdet"],
        "relative_path": "sgtr/vg/sgtr_vg_new_pth/model_0095999.pth",
        "required_paths": ["sgtr/vg/sgtr_vg_new_pth/config.json"],
        "download": {
            "kind": "url",
            "url": "https://shanghaitecheducn-my.sharepoint.com/:u:/g/personal/lirj2_shanghaitech_edu_cn/ESr2lrq30vdLg2nv-d32J6EBRhng0PHsmmdttrAPaSut3g?e=BDlKBg",
        },
        "download_status": "manual_official_portal",
        "download_note": "Download and extract the official SGTR VG archive, retaining model_0095999.pth and config.json in the catalogued directory.",
        "reference_metrics": {"SGDet/mR@50": 12.6, "SGDet/R@50": 24.8},
    },
    "sgtr_oi": {
        "repository": "sgtr",
        "dataset": "oi",
        "architecture": "SGTR",
        "supported_tasks": ["sgdet"],
        "relative_path": "sgtr/oi/sgtr_oiv6_new/model_0107999.pth",
        "required_paths": ["sgtr/oi/sgtr_oiv6_new/config.json"],
        "download": {
            "kind": "url",
            "url": "https://shanghaitecheducn-my.sharepoint.com/:u:/g/personal/lirj2_shanghaitech_edu_cn/ETWYQ6nGWyRGgZAOfS7jOQwB4M19rTobmpCn0RBR0mZFCA?e=lGMhoK",
        },
        "download_status": "manual_official_portal",
        "download_note": "Download and extract the official SGTR OIv6 archive, retaining model_0107999.pth and config.json in the catalogued directory.",
        "reference_metrics": {},
    },
    "motifs_vg": {
        "repository": "microsoft_sgg",
        "dataset": "vg",
        "architecture": "Neural Motifs",
        "supported_tasks": ["predcls", "sgcls", "sgdet"],
        "relative_path": "microsoft/vg/motifs_bias/model_final.pth",
        "download": {
            "kind": "url",
            "url": "https://penzhanwu2.blob.core.windows.net/sgg/sgg_benchmark/sgg_model_zoo/visualgenome/nm_usefpTrue_lr0.015_bsz8_objctx0_edgectx2_shareboxFalse/model_final.pth",
        },
        "download_status": "retired_official_url",
        "download_note": "The published Azure Storage account now returns NXDOMAIN; provide a verified local checkpoint or retrain.",
        "config": "sgg_configs/vg_vrd/rel_danfeiX_FPN50_nm.yaml",
        "reference_metrics": {
            "PredCls/R@50": 61.2,
            "SGCls/R@50": 35.1,
            "SGDet/R@50": 30.1,
        },
    },
    "grcnn_vg": {
        "repository": "microsoft_sgg",
        "dataset": "vg",
        "architecture": "GRCNN",
        "supported_tasks": ["predcls", "sgcls", "sgdet"],
        "relative_path": "microsoft/vg/grcnn_bias/model_0060000.pth",
        "download": {
            "kind": "url",
            "url": "https://penzhanwu2.blob.core.windows.net/sgg/sgg_benchmark/sgg_model_zoo/visualgenome/grcnn_usefpTrue_lr0.005_bsz4_featstep2_scorestep2/model_0060000.pth",
        },
        "download_status": "retired_official_url",
        "download_note": "The published Azure Storage account now returns NXDOMAIN; provide a verified local checkpoint or retrain.",
        "config": "sgg_configs/vg_vrd/rel_danfeiX_FPN50_grcnn.yaml",
        "reference_metrics": {
            "PredCls/R@50": 59.9,
            "SGCls/R@50": 34.9,
            "SGDet/R@50": 30.1,
        },
    },
    "reldn_vg": {
        "repository": "microsoft_sgg",
        "dataset": "vg",
        "architecture": "RelDN",
        "supported_tasks": ["predcls", "sgcls", "sgdet"],
        "relative_path": "microsoft/vg/reldn/model_final.pth",
        "download": {
            "kind": "url",
            "url": "https://penzhanwu2.blob.core.windows.net/sgg/sgg_benchmark/sgg_model_zoo/visualgenome/reldn_usefpTrue_lr0.005_bsz4/model_final.pth",
        },
        "download_status": "retired_official_url",
        "download_note": "The published Azure Storage account now returns NXDOMAIN; provide a verified local checkpoint or retrain.",
        "config": "sgg_configs/vg_vrd/rel_danfeiX_FPN50_reldn.yaml",
        "reference_metrics": {
            "PredCls/R@50": 60.9,
            "SGCls/R@50": 35.7,
            "SGDet/R@50": 32.4,
        },
    },
    "reldn_oi": {
        "repository": "microsoft_sgg",
        "dataset": "oi",
        "architecture": "RelDN",
        "supported_tasks": ["sgdet"],
        "relative_path": "microsoft/oi/reldn/oi_R152_reldn.pth",
        "download": {
            "kind": "url",
            "url": "https://penzhanwu2.blob.core.windows.net/sgg/sgg_benchmark/sgg_model_zoo/oi_R152_reldn.pth",
        },
        "download_status": "retired_official_url",
        "download_note": "The published Azure Storage account now returns NXDOMAIN; provide a verified local checkpoint or retrain.",
        "config": "sgg_configs/oi_vrd/R152FPN_reldn_oi.yaml",
        "reference_metrics": {"SGDet/R@50": 75.40},
    },
    "egtr_vg": {
        "repository": "egtr",
        "dataset": "vg",
        "architecture": "EGTR",
        "supported_tasks": ["sgdet"],
        "relative_path": "egtr/vg/egtr_vg.tar.gz",
        "runtime_checkpoint": "egtr/vg/runtime/model.ckpt",
        "runtime_config": "egtr/vg/runtime/config.json",
        "checkpoint_member": "epoch=03-validation_loss=1.71.ckpt",
        "download": {"kind": "gdrive", "id": "18phcRxbrEI7HqIuM2OLAPuwAF5k3pUC2"},
        "reference_metrics": {},
    },
    "egtr_oi": {
        "repository": "egtr",
        "dataset": "oi",
        "architecture": "EGTR",
        "supported_tasks": ["sgdet"],
        "relative_path": "egtr/oi/egtr_oi.tar.gz",
        "runtime_checkpoint": "egtr/oi/runtime/model.ckpt",
        "runtime_config": "egtr/oi/runtime/config.json",
        "checkpoint_member": "epoch=26-validation_loss=1.06.ckpt",
        "download": {"kind": "gdrive", "id": "1JqWNwf1QvDsTbGFigEXXN_8qv3VF-lGP"},
        "reference_metrics": {},
    },
    "openpsg_motifs_psg": {
        "repository": "openpsg",
        "dataset": "psg",
        "architecture": "Neural Motifs",
        "supported_tasks": ["sgdet"],
        "relative_path": "openpsg/psg/motifs/epoch_12.pth",
        "download": {
            "kind": "url",
            "url": "https://entuedu-my.sharepoint.com/:f:/g/personal/jingkang001_e_ntu_edu_sg/Eh4hvXIspUFKpNa_75qwDoEBJTCIozTLzm49Ste6HaoPow?e=ZdAs6z",
        },
        "download_status": "manual_official_portal",
        "download_note": "The official OpenPSG link is a SharePoint folder; download its checkpoint in a browser and place it at this path.",
        "sha256": "956471959ca89acae45c9533fb9f9a6544e650b8ea18fe62cdead495b38751b8",
        "reference_metrics": {"SGDet/mR@50": 9.57, "SGDet/R@50": 21.7},
    },
    "openpsg_vctree_psg": {
        "repository": "openpsg",
        "dataset": "psg",
        "architecture": "VCTree",
        "supported_tasks": ["sgdet"],
        "relative_path": "openpsg/psg/vctree/epoch_12.pth",
        "download": {
            "kind": "url",
            "url": "https://entuedu-my.sharepoint.com/:f:/g/personal/jingkang001_e_ntu_edu_sg/EhKfi9kqAd9CnSoHztQIChABeBjBD3hF7DflrNCjlHfh9A?e=lWa1bd",
        },
        "download_status": "manual_official_portal",
        "download_note": "The official OpenPSG link is a SharePoint folder; download its checkpoint in a browser and place it at this path.",
        "sha256": "e5fdac7e6cc8d9af7ae7027f6d0948bf414a4a605ed5db4d82c5d72de55c9b58",
        "reference_metrics": {"SGDet/mR@50": 10.2, "SGDet/R@50": 22.1},
    },
    "openpsg_psgtr_psg": {
        "repository": "openpsg",
        "dataset": "psg",
        "architecture": "PSGTR",
        "supported_tasks": ["sgdet"],
        "relative_path": "openpsg/psg/psgtr/epoch_60.pth",
        "download": {
            "kind": "url",
            "url": "https://huggingface.co/spaces/ECCV2022/PSG/resolve/main/OpenPSG/checkpoints/epoch_60.pth",
        },
        "sha256": "1c4ddcbda74686568b7e6b8145f7f33030407e27e390c37c23206f95c51829ed",
        "reference_metrics": {"SGDet/mR@50": 20.8, "SGDet/R@50": 34.4},
    },
    "openpsg_psgformer_psg": {
        "repository": "openpsg",
        "dataset": "psg",
        "architecture": "PSGFormer",
        "supported_tasks": ["sgdet"],
        "relative_path": "openpsg/psg/psgformer/epoch_60.pth",
        "download": {
            "kind": "url",
            "url": "https://entuedu-my.sharepoint.com/:f:/g/personal/jingkang001_e_ntu_edu_sg/EnaJchJzJPtGrkl4k09evPIB5JUkkDZ2tSS9F-Hd-1KYzA?e=9QA8Nc",
        },
        "download_status": "manual_official_portal",
        "download_note": "The official OpenPSG link is a SharePoint folder; download its checkpoint in a browser and place it at this path.",
        "sha256": "2f0015ce67040fa00b65986f6ce457c4f8cc34720f7e47a656b462b696a013b7",
        "reference_metrics": {"SGDet/mR@50": 17.0, "SGDet/R@50": 19.6},
    },
    "pgsg_vg": {
        "repository": "pgsg",
        "dataset": "vg",
        "architecture": "PGSG",
        "supported_tasks": ["sgdet"],
        "relative_path": "pgsg/vg/vg_sgg.pth",
        "download": {
            "kind": "url",
            "url": "https://huggingface.co/rj979797/PGSG-CVPR2024/resolve/main/vg_sgg.pth",
        },
        "reference_metrics": {"SGDet/mR@50": 9.0, "SGDet/R@50": 17.7},
    },
    "pgsg_psg": {
        "repository": "pgsg",
        "dataset": "psg",
        "architecture": "PGSG",
        "supported_tasks": ["sgdet"],
        "relative_path": "pgsg/psg/psg_sgg.pth",
        "download": {
            "kind": "url",
            "url": "https://huggingface.co/rj979797/PGSG-CVPR2024/resolve/main/psg_sgg.pth",
        },
        "reference_metrics": {"SGDet/mR@50": 14.5, "SGDet/R@50": 25.8},
    },
    "ovsgtr_vg_closed": {
        "repository": "ovsgtr",
        "dataset": "vg",
        "architecture": "OvSGTR",
        "supported_tasks": ["sgdet"],
        "relative_path": "ovsgtr/vg/vg-swint-full.pth",
        "download": {
            "kind": "url",
            "url": "https://huggingface.co/JosephZ/OvSGTR/resolve/main/vg-swint-full.pth",
        },
        "sha256": "8961ee968ff544ced541ffdf438ff3367547de57f8a4f2fc9ec8e4330a92a6de",
        "reference_metrics": {"SGDet/R@50": 35.82},
    },
    "ovsgtr_vg_open": {
        "repository": "ovsgtr",
        "dataset": "vg",
        "architecture": "OvSGTR",
        "supported_tasks": ["sgdet"],
        "relative_path": "ovsgtr/vg/vg-ovdr-swint.pth",
        "download": {
            "kind": "url",
            "url": "https://huggingface.co/JosephZ/OvSGTR/resolve/main/vg-ovdr-swint.pth",
        },
        "sha256": "526d459e4fec7ebe9ffe3f4cb64193e7ba6e3d54584711352b49b91a82c65542",
        "reference_metrics": {"SGDet/R@50": 13.50},
    },
}


CORE_MODELS = tuple(
    name for name, spec in MODELS.items()
    if spec.get("download_status", "available") == "available"
)
MANUAL_MODELS = tuple(name for name in MODELS if name not in CORE_MODELS)
SURVEY_REPOSITORIES = tuple(REPOSITORIES)
