#!/usr/bin/env bash
set -euo pipefail

ROOT="${SGG_PROJECT_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
PYTHON="${PYSGG_PYTHON:-python3}"
CORE_PYTHON="${SGG_PYTHON:-python3}"
REPO="$ROOT/external/official_repos/PySGG"
CACHE="$ROOT/artifacts/prediction_cache/pysgg_bgnn_vg_sgdet_official"
CHECKPOINT="$ROOT/checkpoints/sgg/weights/pysgg/vg/bgnn_vg.pth"
CONFIG="$ROOT/configs/pysgg_vg_tritask/bgnn_sgdet.yaml"
MANIFEST="$ROOT/checkpoints/sgg/manifests/pysgg_bgnn_vg_sgdet.json"
SMOKE_RUNTIME="$ROOT/artifacts/smoke/pysgg_bgnn_sgdet/runtime/sgdet"

export PYTHONPATH="$ROOT/legacy_runtime:$REPO:$ROOT${PYTHONPATH:+:$PYTHONPATH}"
cd "$ROOT"

# Reuse the task-identical VG statistics generated by the required smoke run.
mkdir -p "$CACHE/runtime/sgdet"
if compgen -G "$SMOKE_RUNTIME/*.cache" >/dev/null; then
  cp -a "$SMOKE_RUNTIME"/*.cache "$CACHE/runtime/sgdet/"
fi

CUDA_VISIBLE_DEVICES="${PYSGG_GPU:-1}" "$PYTHON" \
  scripts/export_pysgg_vg_task.py \
  --project_root "$ROOT" \
  --config "$CONFIG" \
  --checkpoint "$CHECKPOINT" \
  --task sgdet \
  --name pysgg_bgnn_vg_sgdet_official \
  --family BGNN \
  --output_dir "$CACHE" \
  --eval_samples 26446 \
  --resume --log_every 50

"$CORE_PYTHON" scripts/finalize_pysgg_vg_tritask_cache.py \
  --cache_root "$CACHE" --tasks sgdet --expected_images 26446
"$CORE_PYTHON" scripts/register_pysgg_vg_tritask_manifest.py \
  --project_root "$ROOT" --model bgnn --cache_root "$CACHE" \
  --tasks sgdet --output "$MANIFEST"

echo "[complete] released BGNN SGDet cache=$CACHE manifest=$MANIFEST"
